package br.com.testkotlinboot.pocKotlinBoot.asecurity

import org.springframework.security.web.context.AbstractSecurityWebApplicationInitializer


class SecurityWebApplicationInitializer : AbstractSecurityWebApplicationInitializer()